version: '3.8'
services:
    app:
        image: ${DOCKER_USERNAME}/goody:latest
        ports:
            - '3000:3000'
        volumes:
            - /home/code/goody_prod/.env.local:/app/.env.local
        environment:
            - NODE_ENV=production
