version: '3'

services:
    app:
        image: ajesuscode/goody:latest
        environment:
            SUPABASE_URL: ${SUPABASE_URL}
            SUPABASE_KEY: ${SUPABASE_KEY}
        ports:
            - '3000:3000'
