name: Production Deployment

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/goody:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/goody:latest
                  platforms: linux/amd64

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create .env.local file
              run: |
                  echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env.local
                  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_KEY }}" >> .env.local

            - name: Deploy to Production Server
              env:
                  PRODUCTION_SERVER_HOST: ${{ secrets.PRODUCTION_SERVER_HOST }}
                  PRODUCTION_SERVER_USER: ${{ secrets.PRODUCTION_SERVER_USER }}
                  PRODUCTION_SERVER_PRIVATE_KEY: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
              run: |
                  # Setup SSH
                  mkdir -p ~/.ssh/
                  echo "$PRODUCTION_SERVER_PRIVATE_KEY" > ~/.ssh/production.key
                  chmod 600 ~/.ssh/production.key
                  ssh-keyscan -H $PRODUCTION_SERVER_HOST >> ~/.ssh/known_hosts

                  # Secure Copy to Server
                  scp -i ~/.ssh/production.key .env.local $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER_HOST:/home/code/goody_prod/
                  scp -i ~/.ssh/production.key docker-compose.yml $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER_HOST:/home/code/goody_prod/

                  # Execute Docker Compose
                  ssh -i ~/.ssh/production.key $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER_HOST "cd /home/code/goody_prod && docker compose up -d"
