name: Create and Publish Release
on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Release
              id: create_release
              uses: actions/create-release@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GOODY_RELEASE_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
